#  function OneDec(c) 
#  function TwoDec(c) 
#  function ThreeDec(c) 
#  function FourDec(c) 
#  function scientificNotation(c,e)
#  function radToDeg(angleRad) 
#  function degToRad(angleDeg) 
#  function arrayMinIndex (array) 
#  function arrayMaxIndex (array) 
#  function linspace(x0, xN, dx)
#  function getBaseLog(x, y) 
#  function pnorm(z,tail) 
#  function qnorm(p) 
#  function reducewind(x,ref,fin)   
#  function erf(x) 
#  function ExcelDateToJSDate(serial) 
#  function getDOY(datetime) 
#  function toJulian(date) 
#  function fromJulian(j)  
#  function toDays(date)  
#  function parseISO8601String(dateString) 
#  function isLeapYear(yr) 
#  function dayname_IT(date) 
#  function sun_data(strtime,lat,lon,parameter) 
#  function radtheoric(jddate,elev,albedo,param)
#  function rad_direct_tilted(jddate,az,elev,planezen,planeaz) 
#  function proj(sunelev)
#  function C2F(C) 
#  function F2C(F) 
#  function compass_16(direction) 
#  function compass_8(direction) 
#  function mrt_solar_proj(t,rh,solar,sunelev,albedo,emis_sfc,fdir)
#  function mrt_thorsson(t, tg, wind, diam)
#  function fglob_sphere(Tglobe_prev,Tair,rh,speed,solar,zenith,pair,alb_sfc,fdir,diam)
#  function tglob_sphere(t,rh,speed,solar,zenith,pair,alb_sfc,fdir,diam,maxair,minair,prec)
#  function mrt_globe(t, tg, wind, diam_globe,emis_globe)
#  function wetbulb_stull(t,rh) 
#  function fnatural_wetbulb(Twb_prev,Tair,rh,wspeed,solar,zenith,pair,alb_sfc,fdir,irad)
#  function natural_wetbulb(t,rh,wspeed,solar,zenith,pair,alb_sfc,fdir,irad,maxair,minair,prec)
#  function h_sphere_in_air(tk,speed,pair,speedmin,diam_globe)
#  function h_cylinder_in_air(tk,speed,pair,speedmin,diam_wick)
#  function h_evap(tk)
#  function emis_atm(tk,rh)
#  function esat (tk) 
#  function viscosity(tk)
#  function diffusivity(tk, pair) 
#  function fRH(t,td)
#  function pvsIce(T) 
#  function pvsWater(T) 
#  function PVS(t)
#  function deficitsat(t,rh) 
#  function es(t)
#  function pvap(t,rh)
#  function dewpoint(t,rh,formula) 
#  function humrat(p,pa) 
#  function enthalpy(t, hum_ratio) 
#  function spvol(t,hum_ratio,pa) 
#  function metabolism(t)
#  function PPD(PMV) 
#  function balancePMV7730(pmv,M) 
#  function HB_bmr_met(mbody,age,ht,gender) 
#  function PMV_custom(t,rh,wind,mtrad,iclo,age,mbody,ht,gender)
#  function perceived_temperature(t,rh,wind,tr,M,W,clo) 
#  function PMV_ISO7730(t,rh,wind,trad,M,W,clo) 
#  function HSI_index(t,rh,wind,trad,M,W,clo,param) 
#  function clomax_7730(t,rh,wind,trad,M,W) 
#  function clomin_7730(t,rh,wind,trad,M,W) 
#  function clomax_custom(t,rh,wind,mtrad,age,mbody,ht,gender) 
#  function clomin_custom(t,rh,wind,mtrad,age,mbody,ht,gender) 
#  function pierceSET (t,rh,wind,trad,M,W,clo,patm) 
#  function ta_comfort(rh, wind,M,clo,H)
#  function IREQ(t,rh,wind,trad,M,W,clo,param,p,w) 
#  function recovery_time(t,rh,wind,trad,M,W,clo,p,w) 
#  function UTCI(ta,rh,wind,tmrt)  
#  function heatindex(t,rh)
#  function steadman_outdoor(t,rh,wind,solar,sunelev)
#  function steadman_outdoor_shade(t,rh,wind)
#  function steadman_indoor(t,rh)
#  function utci_class(t,rh,wind,trad) 
#  function utci_class7(t,rh, wind,trad) 
#  function sharlau_index_state(t,rh) 
#  function sharlau_index_delta(t,rh) 
#  function RSI_index(t,rh) 
#  function humidex(t,rh)
#  function THI(t,rh) 
#  function THI_kliber(t,rh) 
#  function oxford_index(t,rh,wind,pair)  
#  function discomfort_index(t,rh,wind,pair)   
#  function fits_index(t,rh,wind,pair) 
#  function lost_productivity(wbgt,tresh)   
#  function BMW(h,w) 
#  function BSA(h,w) 
#  function met_rate(BSA, isolevel) 
#  function rel_acclimatized(met) 
#  function ral_unacclimatized(met) 
#  function heat_risk_text_level(wbgt,cav,tresh)   
#  function heat_risk_text_level_eng(wbgt,cav,tresh)   
#  function heat_risk_color_level(wbgt,cav,tresh)     
#  function heat_risk_hexrgb_level(wbgt,cav,tresh)     
#  function heat_risk_index_value(wbgt,cav,tresh)     
#  function wbdt(t,rh,pair) 
#  function wbgt_sun(t,rh,wind,solar,zenith,pair,alb_sfc,fdir,irad,diam,maxair,minair,prec) 
#  function wbgt_shade(t,rh,wind,pair,alb_sfc,fdir,diam,prec) 
#  function wbgt_stull(t,rh,tg) 
#  function wbgt_indoor(t,rh,wind,pair,elev) 
#  function mdi_index(t,rh,wind,pair)    
#  function thom(t,rh,pair,wind) 
#  function windchill(t, wind) 
#  function wc_watt2mq (t, wind)
#  function windchill_cla(t,wind)
#  function frostime(t,wind)
#  function net_index(t,rh,wind)
#  function ssi_index(t,rh)
#  function p_local(press,elev,temp)
#  function pheight(press,elev)
#  function poda(t,rh,pair)
#  function vpaTorr(t) 
#  function mbtommHG(mb)
#  function torr2p(vp,vpunits)
#  function mbtoinHG(mb)
#  function mbtokPA(mb)
#  function mbtolbsinch(mb)
#  function mph2knots(mph)
#  function mph2ms(mph)
#  function mph2fts(mph)
#  function mph2kmh(mph)
#  function knots2mph(knots)
#  function knots2ms(knots)
#  function knots2fts(knots)
#  function knots2kmh(knots)
#  function ms2mph(ms)
#  function ms2knots(ms)
#  function ms2fts(ms)
#  function ms2kmh(ms)
#  function fts2mph(fts)
#  function fts2knots(fts)
#  function fts2ms(fts)
#  function fts2kmh(fts)
#  function kmh2mph(kmh)
#  function kmh2knots(kmh)
#  function kmh2ms(kmh)
#  function kmh2fts(kmh)
